// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SassyGurl.Api.Data;

#nullable disable

namespace SassyGurl.Api.Migrations
{
    [DbContext(typeof(SassyGurlDbContext))]
    [Migration("20260430121907_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "KycStatus", "kyc_status", new[] { "unverified", "pending", "verified", "rejected", "banned" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "MutationType", "mutation_type", new[] { "deposit", "payment", "refund", "commission", "withdrawal", "adjustment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "OrderStatus", "order_status", new[] { "pending", "processing", "success", "error", "partial", "refunding", "cancelled", "refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "PaymentStatus", "payment_status", new[] { "unpaid", "pending", "paid", "expired", "failed", "refunded", "chargeback" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "PaymentType", "payment_type", new[] { "ewallet", "qris", "virtual_account", "retail" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "PromoType", "promo_type", new[] { "fixed", "percentage" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Role", "role", new[] { "member", "reseller", "vip", "cs", "finance", "superadmin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "TicketPriority", "ticket_priority", new[] { "low", "medium", "high", "urgent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "TicketStatus", "ticket_status", new[] { "open", "in_progress", "waiting_user", "resolved", "closed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SassyGurl.Api.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("accessToken");

                    b.Property<int?>("ExpiresAt")
                        .HasColumnType("integer")
                        .HasColumnName("expiresAt");

                    b.Property<string>("IdToken")
                        .HasColumnType("text")
                        .HasColumnName("idToken");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("providerAccountId");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refreshToken");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("SessionState")
                        .HasColumnType("text")
                        .HasColumnName("sessionState");

                    b.Property<string>("TokenType")
                        .HasColumnType("text")
                        .HasColumnName("tokenType");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderAccountId")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Banner")
                        .HasColumnType("text")
                        .HasColumnName("banner");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoryId");

                    b.Property<string>("GuideImage")
                        .HasColumnType("text")
                        .HasColumnName("guideImage");

                    b.Property<bool>("HasServerId")
                        .HasColumnType("boolean")
                        .HasColumnName("hasServerId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsHot")
                        .HasColumnType("boolean")
                        .HasColumnName("isHot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<string>("ServerOptions")
                        .HasColumnType("jsonb")
                        .HasColumnName("serverOptions");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.PaymentMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<decimal>("FeeFlat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("feeFlat");

                    b.Property<decimal>("FeePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("feePercent");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gameId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsFlashSale")
                        .HasColumnType("boolean")
                        .HasColumnName("isFlashSale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("originalPrice");

                    b.Property<decimal>("PriceMember")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("priceMember");

                    b.Property<decimal>("PriceModal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("priceModal");

                    b.Property<decimal>("PriceReseller")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("priceReseller");

                    b.Property<decimal>("PriceSell")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("priceSell");

                    b.Property<decimal>("PriceVip")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("priceVip");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("providerId");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("Sku", "GameId", "IsActive");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Promo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("maxDiscount");

                    b.Property<decimal>("MinTransaction")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("minTransaction");

                    b.Property<int>("Quota")
                        .HasColumnType("integer")
                        .HasColumnName("quota");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("usedCount");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Promo", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Provider", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AvgLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("avgLatencyMs");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("balance");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("SuccessRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("successRate");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Provider", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gameId");

                    b.Property<string>("Images")
                        .HasColumnType("jsonb")
                        .HasColumnName("images");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transactionId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "Rating");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.SupportTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticketNumber");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transactionId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("SupportTicket", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.SystemAudit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actionBy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entityId");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ipAddress");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("newValues");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("oldValues");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("userAgent");

                    b.HasKey("Id");

                    b.HasIndex("ActionBy", "Entity", "CreatedAt");

                    b.ToTable("SystemAudit", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.TicketMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Attachments")
                        .HasColumnType("jsonb")
                        .HasColumnName("attachments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senderId");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticketId");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMessage", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("AdminFee")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("adminFee");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DenomName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("denomName");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("discount");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiredAt");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gameId");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoiceId");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer")
                        .HasColumnName("orderStatus");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paidAt");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paymentId");

                    b.Property<string>("PaymentRef")
                        .HasColumnType("text")
                        .HasColumnName("paymentRef");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("paymentStatus");

                    b.Property<decimal>("PriceModal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("priceModal");

                    b.Property<decimal>("PriceSell")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("priceSell");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productId");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("profit");

                    b.Property<string>("PromoId")
                        .HasColumnType("text")
                        .HasColumnName("promoId");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("text")
                        .HasColumnName("providerRef");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Sn")
                        .HasColumnType("text")
                        .HasColumnName("sn");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("targetId");

                    b.Property<string>("TargetName")
                        .HasColumnType("text")
                        .HasColumnName("targetName");

                    b.Property<decimal>("TaxVat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("taxVat");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totalAmount");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.Property<string>("WebhookData")
                        .HasColumnType("jsonb")
                        .HasColumnName("webhookData");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zoneId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GameId");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.HasIndex("PaymentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PromoId");

                    b.HasIndex("TargetId");

                    b.HasIndex("UserId");

                    b.HasIndex("InvoiceId", "PaymentStatus", "OrderStatus");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("deviceId");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emailVerified");

                    b.Property<string>("IdCardImage")
                        .HasColumnType("text")
                        .HasColumnName("idCardImage");

                    b.Property<string>("IdCardNumber")
                        .HasColumnType("text")
                        .HasColumnName("idCardNumber");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsTwoFactorEnable")
                        .HasColumnType("boolean")
                        .HasColumnName("isTwoFactorEnable");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("isVerified");

                    b.Property<int>("KycStatus")
                        .HasColumnType("integer")
                        .HasColumnName("kycStatus");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("text")
                        .HasColumnName("lastLoginIp");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referralCode");

                    b.Property<string>("ReferrerId")
                        .HasColumnType("text")
                        .HasColumnName("referrerId");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text")
                        .HasColumnName("taxNumber");

                    b.Property<decimal>("TotalCommission")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("totalCommission");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdCardNumber")
                        .IsUnique();

                    b.HasIndex("KycStatus");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.HasIndex("ReferrerId");

                    b.HasIndex("Email", "Phone", "ReferralCode");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.VerificationToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("Identifier", "Token")
                        .IsUnique();

                    b.ToTable("VerificationToken", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.WalletLedger", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("BalanceSnapshot")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("balanceSnapshot");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("debit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PerformedById")
                        .HasColumnType("text")
                        .HasColumnName("performedById");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transactionId");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId", "Type", "CreatedAt");

                    b.ToTable("WalletLedger", (string)null);
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Account", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Game", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Product", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.Game", "Game")
                        .WithMany("Products")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SassyGurl.Api.Models.Provider", "Provider")
                        .WithMany("Products")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Review", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SassyGurl.Api.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.SupportTicket", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.SystemAudit", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.User", "Admin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActionBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.TicketMessage", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Transaction", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.Game", "Game")
                        .WithMany("Transactions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SassyGurl.Api.Models.PaymentMethod", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SassyGurl.Api.Models.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SassyGurl.Api.Models.Promo", "Promo")
                        .WithMany("Transactions")
                        .HasForeignKey("PromoId");

                    b.HasOne("SassyGurl.Api.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId");

                    b.Navigation("Game");

                    b.Navigation("Payment");

                    b.Navigation("Product");

                    b.Navigation("Promo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.User", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.User", "Referrer")
                        .WithMany("Referees")
                        .HasForeignKey("ReferrerId");

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.WalletLedger", b =>
                {
                    b.HasOne("SassyGurl.Api.Models.User", "User")
                        .WithMany("WalletLedgers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Category", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Game", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Reviews");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.PaymentMethod", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Product", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Promo", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.Provider", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SassyGurl.Api.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("AuditLogs");

                    b.Navigation("Referees");

                    b.Navigation("Reviews");

                    b.Navigation("SupportTickets");

                    b.Navigation("Transactions");

                    b.Navigation("WalletLedgers");
                });
#pragma warning restore 612, 618
        }
    }
}
